### ISSUE TITLE
Extension not working for almost any CSS property

### ISSUE THREAD

**Issue by jmalarcon** [akamud/vscode-caniuse#2]
Hi Mahmoud:

First of all think you for the effort taken in creating this extension.

However I've installed it in two computers with Windows 8 and Windows 10 and the latest version of VS Code, and it doesn't seem to work with any CSS property. I always get that there is no information in CanIUse for the property.

I've tested it with the same property you use in your screen capture (`outline`) and it works fine, but any other property simply doesn't work at all,and they are in CanIUse for sure.

Thanks for your work.

**Comment by pdg6805** [comment]
I got the same issue I get the error "Can I use: entry not found"

**Comment by akamud** [comment]
http://caniuse.com database doesn't have all the properties. It mainly shows properties that are new and were not widely supported from the start. 

However, I know that right now there is a problem in the extension related to "mapping" of properties. For example, `max-width` is present in caniuse.com database, but since the rule is registered as ["minmaxwh"](http://caniuse.com/minmaxwh), the extension is not able to find the property when it queries for just `max-width`.

I can fix this creating a dictionary that would map these inconsistencies, which is in the roadmap and I am doing right now. The next version should already come with this feature. Sorry for the weak support at the moment.

Can you show me some examples of properties that you tried so I can confirm this is the case?

Thanks for reporting!

**Comment by jmalarcon** [comment]
Hi again:

Thank you for your response.

Well, I've tried (just for testing the app a little bit) with lots of common properties that probably don't appear because what you said: they are supported everywhere. I didn't know what you have said about the "mapping" thing which I think is a great idea.  

I've tried with "modern" properties, mostly related to animations and transforms, like 'transform' or '@keyframes' and they didn't show up. This and the common properties thing made me think it wasn't working at alll.

Just a suggestion: maybe is a good idea to show full support for all the browsers in all the common properties that CanIUse takes for granted. In that way it will be less misleading if you don't know the ins and outs of how it works.

Thanks again for your work!

**Comment by akamud** [comment]
Thanks for the feedback @jmalarcon. I'll investigate how I can differentiate properties that were not found from properties that are supported everywhere, as caniuse.com does not have this information.

As for the `keyframes` and `transform`, they are great examples of properties that will work when I release the mapping, because caniuse.com has them with different names.

**Comment by jmalarcon** [comment]
Great, thanks!

By the way: I'm writing an article on the best VSCode extensions for web developers (in Spanish, sorry) that I plan to release next week at http://www.campusmvp.es/recursos/ and yours is in the first place :-)

I'll mention that you're adding this mapping to enhance results in a next version.

Thanks!

**Comment by akamud** [comment]
I'm so glad to hear this! I'll put my Spanish classes to test reading your article.

By the way, I plan to release the mapping tonight (50% done), so maybe it will already be more useful when you write your article :)

**Comment by jmalarcon** [comment]
Great!

It's scheduled for next Tuesday. I'll check if there's any updates and update the text accordingly if you release it before that day.

Thanks

**Comment by akamud** [comment]
Thank you so much for reporting this. I now have a [normalized version](https://github.com/akamud/vscode-caniuse/blob/master/data/rulesDictionary.js) generated from the caniuse data file which I'll use as a dictionary before querying. You can see it fixes the two examples above, `keyframes` and `transform`.

![2015-11-26_22-46-38](https://cloud.githubusercontent.com/assets/954102/11432564/98a55f16-948f-11e5-953a-7440e5484b0b.png)

It is already available in version 0.4.0 in the [marketplace](https://marketplace.visualstudio.com/items/akamud.vscode-caniuse).

In the future, if you find any property that **is** present in caniuse.com but is not available in the extension, please raise an issue and I'll add it to the mapping.

**Comment by jmalarcon** [comment]
Great! Thanks.

**Comment by akamud** [comment]
Please let me know if you still have trouble.
