### ISSUE TITLE
I always get a "Can I use: entry not found"

### ISSUE THREAD

**Issue by notbenj** [akamud/vscode-caniuse#3]
Hello,

Thanks for this extension.

However it doesn't work on my computer.

My setup:

* Windows 7 
* VS Code 0.10.2
* Can I Use 0.4.1

I created a *test.css* file with the following content:

```css
a {
  border: white;
}
```

Then when I put my cursor in the border element, or **also when I select it**, and type ctrl + shift + i, I always get a *Can I use: entry not found* in the status bar.

Thanks!

**Comment by akamud** [comment]
We recently talked about cases where I needed to "map" a property to the corresponding caniuse.com rule in #2. Starting from version 0.4.0 the extension now handles these cases much better, so I suggest you check if you have the latest version first.

However, in your case, the `border` property falls into the subset of "well-supported properties", present since CSS 2.1. These properties don't exist in caniuse.com because you can *always* use them. That's why the extension can't find it either.

I see these problems can come up frequently, so I'll think of a way to show a better message in these cases. Are you having trouble with any other property?

**Comment by akamud** [comment]
I added support for CSS 2.1 properties in commit 76a5fe2b1382b7ba8f43a96ed3992d3fa102c9ab. This feature is now available in version [0.5.0](https://marketplace.visualstudio.com/items/akamud.vscode-caniuse)
