### ISSUE TITLE
get "entry not found" after install caniuse in vs code

### ISSUE THREAD

**Issue by wikilike7** [akamud/vscode-caniuse#5]
The environment: windows 10
vs code version: 0.10.11

i press the short key "ctrl+shift+i" to use caniuse but the error message "entry not found" popup

**Comment by akamud** [comment]
Can you provide me with a sample on the code that's causing the issue?

**Comment by wikilike7** [comment]
ok, thank you 
i upload a screenshot for your reference
![caniuse](http://7fv8ts.com1.z0.glb.clouddn.com/caniuse.jpg)

**Comment by akamud** [comment]
Thank you for sending a screenshot.

You get a "entry not found" because you are trying a HTML element that is supported since the beginning, caniuse.com doesn't have a reference for that because there is no need, you can always use it.

This extension is aimed to help you with new elements and selectors, for example, the `<video>` tag was introduced recently, and if you call Can I Use for that, you will get a list of supported browsers.

You can try it with theses CSS properties:
```CSS
boo {
    outline: 1px;
    transform: 1;
    animation-frame: 1;
    matrix: 1;
    keyframe: 1;
}
```

**Comment by wikilike7** [comment]
Thank you for your explain

i try to test HTML 5 new element in VS code as your follow, but it also "entry not found"

by the way, i use vs code in office and our internet access by proxy server

**Comment by akamud** [comment]
If you try to use on that same CSS sample I sent you still get an entry not found?

If that is the case, you might be having the same problem as #4, which was behind a proxy blocking access.

I plan to implement an offline mode in future releases.

**Comment by wikilike7** [comment]
ok, i got it 
i will try this function in my home computer

Any way, thanks
